### ISSUE TITLE
Last BubbleListItem appears silently when SpeedDial is collapsed

### ISSUE THREAD

**Issue by psheehan89** [smollweide/react-speed-dial#10]
I've attached click handlers to each one of my bubble list items and everything works great. However I found a bug where you can still click on the last item in your bubble list my clicking directly above the speed dial. I went to check the examples with the DOM selector and had my thoughts confirmed.

Speed Dial Opened
![image](https://cloud.githubusercontent.com/assets/10932223/23479069/13e1577c-fe78-11e6-9d70-0a3c1cf368ef.png)

Speed Dial Closed
![image](https://cloud.githubusercontent.com/assets/10932223/23478987/dc7e861a-fe77-11e6-8ec7-034f6ded5178.png)

Since I have a click handler on each item, users are erroneously triggering the event when clicking near the dial on the screen.

**Comment by psheehan89** [comment]
I found the bug in  `node_modules/react-speed-dial/components/bubble-list-item/bubble-list-item-styles.js
`

By adding `display: 'none'` to the invisible property, the invisible elements are removed from the DOM. Unfortunately it looks like we lose the neat MUI animation as the icons spring up.

```
visible: {
  main: {
    opacity: 1,
    display: 'inline-flex'
},
```


 
```
 invisible: {
  main: {
    opacity: 0,
    display: 'none'
  },
```

**Comment by psheehan89** [comment]
Doing some research it looks like this is the best implementation. It removes the invisible elements from the DOM while keeping the transitions.

```
visible: {
  main: {
    visibility: 'visible'
},
```
```
 invisible: {
  main: {
    visibility: 'hidden'
  },
```

**Comment by smollweide** [comment]
fixed - thanks :)
