### ISSUE TITLE
How to close SpeedDial when clicking on any BubbleListItem

### ISSUE THREAD

**Issue by raqi1** [smollweide/react-speed-dial#11]
How to close SpeedDial when clicking on any BubbleListItem?

**Comment by smollweide** [comment]
Hi @raqi1,
thanks for the report. That was possible with the onChangeState callback. But I added a new callback called onChange and also an new prop called isOpen. This allows you to use the speed dial as controlled component.

Therefor please install `npm install react-speed-dial@latest --save` or `npm yarn react-speed-dial@0.4.2 --save`

[Controlled SpeedDial example](https://smollweide.github.io/react-speed-dial/#/bug11)

**Comment by smollweide** [comment]
And code example [here](https://github.com/smollweide/react-speed-dial/blob/develop/src/examples/example-bug11/example-bug11.js)

**Comment by smollweide** [comment]
Hi @raqi1,
I found a bug, so please don't use 0.4.2 but 0.4.3 instead.
`npm install react-speed-dial@latest --save` or `yarn add react-speed-dial@0.4.3 --save`

Thank you for your patience.

**Comment by 4ship** [comment]
really appreciate your help. I have another issue

I want to change background and label color for BubbleListItem like this URL : 
https://3.bp.blogspot.com/acVu1CuIrrhZzASjL8oQ9NZKr7Z_O05uZECutYLKu4g=w237-h395-no

I was able to do it for the entire app but I want it only in BubbleListItem

thank you again

**Comment by smollweide** [comment]
Hi @raqi1,
I add the props style and styleTxt for the BubbleListItem component.
`npm install react-speed-dial@latest --save` or `yarn add react-speed-dial@0.4.4 --save`

[example](https://github.com/smollweide/react-speed-dial/blob/master/src/examples/example-bug11/example-bug11.js#L88)

Thank you for your patience.
