### ISSUE TITLE
IE not properly render action button with text-align: center and position: absolute

### ISSUE THREAD

**Issue by twhtanghk** [smollweide/react-speed-dial#19]
It seems that child buttons positioned center with proper margin in IE. Any hints to apply the same style for child buttons to the action button.

![action_button](https://user-images.githubusercontent.com/1798269/27820111-cbc4f2ea-60cf-11e7-9cd0-8ade5f064e29.png)
![child_button](https://user-images.githubusercontent.com/1798269/27820143-f72be3bc-60cf-11e7-9b37-cd29103177a4.png)

**Comment by smollweide** [comment]
Probably a problem with material-ui itself.
