### ISSUE TITLE
Backdrop does not overlay on mobile

### ISSUE THREAD

**Issue by hashwin** [smollweide/react-speed-dial#20]
First off, great project.

When using on a mobile phone, the backdrop option does not act as an overlay, i.e. when clicking outside of a button, the underlying div is clicked.

This only happens when running on the phone (or using the device toolbar on Chrome).
Works fine on a regular browser on a PC.

Any idea why this would differ?

**Comment by smollweide** [comment]
Hi @hashwin,
sorry for the delay.
It's fixed with v0.4.6
