### ISSUE TITLE
Not working Properly in example mouseover

### ISSUE THREAD

**Issue by monikapathania** [smollweide/react-speed-dial#28]
Hi
Thanks for added moreover effect but its not working properly when you hover on floating button the bubble item not stable when you change mouse point its hidden so how we click on bubble item and you please customize like this https://material-ui.com/lab/speed-dial/ and provide us any suggestion how we stable bubble on mouse hover we need same like https://material-ui.com/lab/speed-dial/ 
ThankYou :)

**Comment by smollweide** [comment]
Hi,
thank you.
Both issues should be fixed with 0.5.1.

Greetings,
Simon

**Comment by monikapathania** [comment]
Hi,
Thank You 
Really appreciate your help. there is an issue when we click on the button, then the functionality is working in reverse mode i.e on hover it is closing the list and on moving away it is opening the list. after clicking the button again everything works fine, but this issue repeats on clicking again the button. so hide the auto click fnc. 

please check this link https://www.useloom.com/share/b485c804bcf242afb92f5007dd5094ca

**Comment by monikapathania** [comment]
there is any solution and suggestion?

**Comment by smollweide** [comment]
Hi @monikapathania,
you forgot to reopen the issue, that's why I didn't read the message above.

**Comment by monikapathania** [comment]
oh, can u pls suggest something.

there is an issue when we click on the button, then the functionality is working in reverse mode i.e on hover it is closing the list and on moving away it is opening the list. after clicking the button again everything works fine, but this issue repeats on clicking again the button. so hide the auto click fnc.

please check this link

https://www.useloom.com/share/b485c804bcf242afb92f5007dd5094ca

**Comment by smollweide** [comment]
yes I will disable the onclick when mouseactions are enabled.
That should also work on touch devices.

**Comment by smollweide** [comment]
just updated the demo page:
https://smollweide.github.io/react-speed-dial/#/mouseover

**Comment by smollweide** [comment]
Hi @monikapathania,
the fix is available in v0.5.2. Could you please have a look and close the ticket if okay?

Greetings,
Simon

**Comment by monikapathania** [comment]
Hi simon,
Great!!!
Now its working fine. appreciate your help.
Thankyou
