### ISSUE TITLE
Disable a BubbleListItem?

### ISSUE THREAD

**Issue by gknapp** [smollweide/react-speed-dial#29]
Hi,

Just checked the docs, I couldn't see a `disabled` prop for items? Do I have to not display the item / filter it from `children`?

Useful to show the user it's an available option but temporarily disabled due to an unmet condition.

**Comment by smollweide** [comment]
Hi,
the item has no disable prop because this is not specified in material design. I would recommend to just not render the item. 
https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

**Comment by gknapp** [comment]
Thanks, that's what I ended up doing.
