### ISSUE TITLE
Open Speed dial a different direction

### ISSUE THREAD

**Issue by craig1123** [smollweide/react-speed-dial#4]
How would one customize your library so that the speed dial could open any direction (up, down, right or left)? Right now, it only shoots upwards.

**Comment by smollweide** [comment]
@craig1123:
You can use the props `positionV` and `positionH` for control the SpeedDial position.
In case of you use for example `positionV="top"` and `positionH="right"` the `BubbleList` will popup into the bottom left direction.
[Example code](https://github.com/smollweide/react-speed-dial/blob/master/src/examples/example-top-left/example-top-left.js#L36)
[Full documentation](https://smollweide.github.io/react-speed-dial)

**Comment by craig1123** [comment]
So positionV and positionH control the SpeedDial position. My question is about direction. Check out this library https://onsen.io/v2/docs/react/SpeedDial.html, if you type in "direction="left" on that speed dial, it opens to the left. None of the props for this library make the bubbleListItems slide out to the left/right

**Comment by smollweide** [comment]
Published v0.2.0
- `npm install react-speed-dial@0.2.0`
- [Example](https://smollweide.github.io/react-speed-dial/#/direction)
- [Example code](https://github.com/smollweide/react-speed-dial/blob/master/src/examples/example-direction/example-direction.js)
